name: Demo Push

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

env:
  IMAGE_NAME: digitalresume

jobs:
  push:
    name: Build the image and push to github repository
    # if the pull request is being merged
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/digital-resume:${{ github.run_number }} , ${{ github.repository_owner }}/digital-resume:latest
