name: Demo Push

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

env:
  IMAGE_NAME: digitalresume

jobs:
  push:
    name: Build the image and push to github repository
    # if the pull request is being merged
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to Docker Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: keycache/digital-resume:${{ github.run_number }} , keycache/digital-resume:latest
      -
        name: Run commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SECRET }}
          port: 22
          script: |
            sudo docker pull keycache/digital-resume:latest
            sudo docker stop $(sudo docker ps -q --filter ancestor=keycache/digital-resume:latest) 2>/dev/null
            sudo docker run -d -p 8501:8501 keycache/digital-resume:latest
